#!/bin/bash
create_profile(){
FILE_PROFILE="$HOME/.mozilla/firefox/profiles.ini"
PATH_WEB="/usr/share/doc/lliurex-profile/"

    if [ ! -f $FILE_PROFILE ] ; then
        $(firefox $PATH_WEB/index.html)
    fi

}


# ################ Main ###################

create_profile


exit 0


